### ISSUE TITLE
Can't Resync Wii Controller (cant load system menu from priiloader

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DacoTaco/priiloader#202]
```
What steps will reproduce the problem?
1. softmod wii using instructions in wiihacks.com (priiloader v0.7) was able to 
use wii for several days after softmod
2. now, when I turn on the wii, I get a black screen. 
3.Press reset after turning on wii, Priiloader loads

What is the expected output? What do you see instead?
Supposed to be able to navigate, but my wiimotes are not synced

What version of priiloader are you using? On what ios/system menu?
ver 0.7 (rel 138) iOS 80 system menu 513 (data as seen from priiloader screen)

Do you have any IOS patches installed? (if so which ios and what patch?)
ios 58 and 61 as per wiihacks.com instruction

I read that there was a 15 second reset trick in ver0.3 but I can't get it to 
work.  Is there a new method for ver0.7 so that I can go to the system menu and 
sync the wiimotes? Thanks very much!!

What are your wii system menu settings



```

Original issue reported on code.google.com by `matewry...@gmail.com` on 3 Jan 2015 at 12:57

**Comment by DacoTaco** [comment]
power & reset navigation is only in bootmii, not in priiloader.
however yes a gamecube controller will work, and you can press reset in the priiloader menu (after a few seconds) and it'll boot system menu. in the health screen you can sync wiimotes. however, the original issue was that his wii looked to be bricked and his wiimotes weren't synced (desynced or bluetooth dead).

**Comment by Pysis868** [comment]
Ah, ok, I must have not read it that way when he stated navigating to the system menu.

So the tip is be sure to have a GC controller and whatever Homebrew one could use to unbrick the Wii also supports GC, where Wii Mod Lite might help, and it does support that.
