### ISSUE TITLE
Priiloader download link on WiiBrew broken?

### ISSUE THREAD

**Issue by FuzzyQuills** [DacoTaco/priiloader#204]
So... i went to download priiloader today...
...But the download link on WiiBrew redirects to a blank page. inputting the site itself without the link redirects to a cosplay website...

Has someone hijacked your domain by any chance? And above all, where's the actual download now? I'd rather not have to build from source...

**Comment by FuzzyQuills** [comment]
Ok, adding that indeed, it does appear to be our site, but atm, download link returns an error 500

**Comment by avarun42** [comment]
Did you ever find the download?

**Comment by FuzzyQuills** [comment]
WOW. I completely forgot about this, lol.

I do have Priiloader now, not sure if it was a slightly older version someone else uploaded somewhere, or if I found the download itself. I'll test it again today if you like.

**Comment by NuclearFej** [comment]
[priiloader.zip](https://github.com/DacoTaco/priiloader/files/446237/priiloader.zip)

This is either 0.8 or 0.8.1. META.XML says 0.8 but two downloads I tried both said that it is 0.8.1. Not too many differences between the two anyway.

**Comment by DacoTaco** [comment]
so euh.... i just saw this issue report lol XD

this probably happened when i updated php some time ago. 

thanks @NuclearFej for the mirror. ill see when i can fix this :)

**Comment by DacoTaco** [comment]
ye, it was a PHP function that got deleted in PHP5 (this was a major upgrade of several versions at once XD )

it should be fully functioning again, can you guys confirm?
