### ISSUE TITLE
cIOSPAGHETTI detected

### ISSUE THREAD

**Issue by v0idst4r** [DacoTaco/priiloader#205]
yes hello please remove this darn check

**Comment by DacoTaco** [comment]
why would i? what do you need darkcorp for ?

**Comment by v0idst4r** [comment]
I don't use darkcorp

**Comment by v0idst4r** [comment]
I uninstalled it long ago but it still shows "cIOSPAGHETTI detected"

**Comment by DacoTaco** [comment]
then obviously there is stuff left behind or youre trying to install it using a IOS that has CIOS installed. what IOS is homebrew channel using ?

**Comment by v0idst4r** [comment]
IOS58

**Comment by v0idst4r** [comment]
I ran syscheck and found that some IOS <200 were still cIOS so DARKCORP must've left them, reinstalled every one from NUS and priiloader ran.

**Comment by DacoTaco** [comment]
another reason why things like darkcorp give me the creeps. im happy to see it resolved!
