### ISSUE TITLE
"Press A to exit back to loader"

### ISSUE THREAD

**Issue by Raflos10** [DacoTaco/priiloader#208]
Trying to update, it shows the disclaimer screen then immediately shows "Press A to exit back to loader".

**Comment by Raflos10** [comment]
Note: I'm trying to update from v0.4

**Comment by DacoTaco** [comment]
it should also have given you an error why. do you have Cioscorp or darkcorp installed? are you trying to install using a CIOS ?

**Comment by Raflos10** [comment]
No but its okay, I updated v0.7 and it works fine.
