### ISSUE TITLE
Press A to exit back to loader

### ISSUE THREAD

**Issue by KevinGA270** [DacoTaco/priiloader#213]
![128201](https://user-images.githubusercontent.com/39724755/40645293-284cf2d2-6350-11e8-9aee-a493547c767d.jpg)
![127826](https://user-images.githubusercontent.com/39724755/40645295-28a1bf92-6350-11e8-802d-eb8e80b55c2f.jpg)

hi, my friend wanted to update his priiloader
his wii is running on 4.1U
with priiloader installed V0.6 (r123) iosV60
he's been following all the step, put the Priiloader to app folder and using HBC,
but every time he press the priiloader V0.8 installer
its says "Press A to exit back to loader" then just nothing happened
any suggestion?
thanks!

**Comment by DacoTaco** [comment]
normally there should be a message above the press A to exit line, but it was cut off by the TV.

thankfully i can see what is wrong from your first picture of priiloader.
his wii has been modded with a custom System Menu version and is not supported by priiloader. 

please find a guide to install a normal system menu version before updating priiloader. maybe look around on gbatemp.net. they made that custom system menu version.

**Comment by KevinGA270** [comment]
okay thx for the info ;D
we'll find our way to install the right version of system channel

**Comment by KevinGA270** [comment]
btw what version of wii sys menu that compatible with priiloader?

**Comment by DacoTaco** [comment]
all system menu versions are compatible, but i suggest to install 4.1. its the same version as installed now (please verify in system menu!), safest because no new IOS install is needed

**Comment by MarshTheBacca** [comment]
I'm having a similar issue. I'm running system menu version 4.1E, and using PriiLoader 0.9.1 on a USB, the following happens: Image 1 appears for a split second, followed by image two, which remains until I press A.

**Comment by AndrewPiroli** [comment]
As per syscheck posted on Discord the installed system menu is 'System Menu 4.1E (v54450)'.
This is a modified System Menu and needs to be reinstalled.
