### ISSUE TITLE
Press A to go back to loader

### ISSUE THREAD

**Issue by HeyItsMeNobody** [DacoTaco/priiloader#217]
I saw this on a other error, But I didn’t understand much of it.. I’m on 4.1E with only homebrew and bootmii installed. It shows the splashscreen and then just says “Press a to go back to loader”

**Comment by DacoTaco** [comment]
im going to bombard you with some questions, but they are all kind of important to understand what is going on.

how was the system modded? are you talking about the installer giving this error?

on the splash screen, did you see the version/rev number in the left top corner?
can you run something like syscheck to give me an idea as what the system looks like and why it would not install?
