### ISSUE TITLE
Wiimmfi hack not working in any loader (error 20100)

### ISSUE THREAD

**Issue by OmarRod1314** [DacoTaco/priiloader#245]
The error happens when you try to login into CFW on a game with any USBLoader showing a error 20100, instead of showing the error 20110 or login correctly . 

Swap CIOS or delete savedata don't fix this, i've tested Mario Kart Wii and Smash Bros Brawl and same result.

**Comment by OmarRod1314** [comment]
The error seems to have solved showing the error 20110 again,

**Comment by DacoTaco** [comment]
im sorry, but this is an issue about the wiimmfi hack in an usbloader instead of system menu?

**Comment by OmarRod1314** [comment]
Yes.

**Comment by DacoTaco** [comment]
then im sorry, but this hack is only for games loaded through system menu. priiloader can not change how games behave loaded in any other way (as priiloader can only change what system menu does )
