### ISSUE TITLE
Syntax error given from change on commit 17860a9

### ISSUE THREAD

**Issue by povanspring** [DacoTaco/priiloader#246]
**Describe the bug**
A syntax error is thrown from Priiloader when loading `hacks_hash.ini` from commit `17860a9`

**To Reproduce**
Use `hacks_hash.ini` from commit `17860a9`.

**Version**
`Priiloader 0.8.2`

**Expected behavior**
Not a syntax error, should show the hacks list.

**Comment by DacoTaco** [comment]
obviously the hacks hash from that version is going to throw an error...

the hacks file (including the 420p hack) contains hacks and new syntaxes introduced in Priiloader 0.9 ...

try again with Priiloader 0.9
