### ISSUE TITLE
Priiloader (0.9.b4) does not appear while pressing ESC on Wii Mini

### ISSUE THREAD

**Issue by buggii** [DacoTaco/priiloader#256]
Hi my friend.

I just tested latest 0.9.b4; it does not hang anymore waiting for a keybpress at boot but Priiloader does not start if ESC keyboard key is hold at boot. I used the latest installer on the github page.

**Comment by DacoTaco** [comment]
is this always on boot?
cause with that keyboard it seems to work here :/

also, with beta 3 it worked, right? :/

**Comment by DacoTaco** [comment]
yup, totally worth it that i bought the keyboard haha.

i think i got something.
can you install this and try : http://upload.dacotaco.com/boot_kb_wakeup.dol

**Comment by buggii** [comment]
Test done ! Now it is working fine ! Thank you !
