### ISSUE TITLE
new wiimmfi update required. 

### ISSUE THREAD

**Issue by TheTechRobo** [DacoTaco/priiloader#272]
![image](https://user-images.githubusercontent.com/52163910/109334075-3cdedf80-782e-11eb-8051-8dd9515d1c7b.png)

looks like wiimmfi patch needs an update.

**Comment by DacoTaco** [comment]
yes, i know.
he contacted me a few minutes ago.
i told him that when the priiloader hack update is done, he should open a pull request to the release branch and i'll pull in the update :)

it should also say that further down the post, does it not?

**Comment by TheTechRobo** [comment]
yeah, but wanted to make sure you new. :+1:

**Comment by DacoTaco** [comment]
thanks ! :)

**Comment by TheTechRobo** [comment]
Merged.
