### ISSUE TITLE
vWii Priiloader support

### ISSUE THREAD

**Issue by LegendaryGamerLand36** [DacoTaco/priiloader#297]
Hello there I'm a fellow vWii modder since I dont have an actual Wii but i was wondering if you like to send me the code or the Files for Priiloader for i can install it in my Wii Us virtual Wii I understand if you dont want to share it with me-
with regards- Miguel

**Comment by DacoTaco** [comment]
Hi,

I don't want to sound rude, but please look at #268 . 
the problem with vWii is that the cpu requires an encrypted and signed binary. it won't run anything else.
channels are started through some special IOS, but system menu must be a complete, ancast image.
this is why priiloader has not been made vWii compatible yet.
any priiloader on vwii image or content i made was produced by putting priiloader in HBC, which is not what we want.
