### ISSUE TITLE
Hi, sorry it's not a issue.

### ISSUE THREAD

**Issue by Alexyo21** [DacoTaco/priiloader#303]
Hi again, I don't know to contact you for a new idea if we can call it. If you don't mind, is there a place where can I write to you?

**Comment by DacoTaco** [comment]
ideas ( or RFC/**R**equest **F**or **C**hange ) can be done through the issue tracker , no problem.
see things like #299 or #268 :)

if you want to have a lengthy chat about it feel free to contact me in the /r/wiihacks discord

**Comment by Alexyo21** [comment]
Thank you very much, and sorry for bothering. I'll write it there because here it's not most easy. I'm on phone browser.
