### ISSUE TITLE
"Loading disc" not working

### ISSUE THREAD

**Issue by PownicMania** [DacoTaco/priiloader#311]
**Describe the bug**
I tried to load my Mario Kart Wii disc through the "Load disc" feature in Priiloader twice, yet it didn't load the game at all. The first time even had a glitched green screen.

**To Reproduce**
Have Mario Kart Wii on your disc drive
Load it via Priiloader

**Version**
0.10.0 Beta 1

**Expected behavior**
Load the game successfully

**Comment by TheTechRobo** [comment]
Could you enable logging and post the Prii.log file?

**Comment by DacoTaco** [comment]
and on top of that log, does the game work when loaded from system menu/another source?

**Comment by PownicMania** [comment]
> and on top of that log, does the game work when loaded from system menu/another source?

It works just fine on the system menu

> Could you enable logging and post the Prii.log file?

How do you enable logging? I don't see it anywhere

**Comment by DacoTaco** [comment]
it should be in the settings, i think its name is "dump debug info" or something along the lines.

sadly i don't own a copy of mario kart on the wii to try this out with :/ 
@TheTechRobo  : do you have the game, and can you try?

**Comment by TheTechRobo** [comment]
I have Mario Kart Wii for NTSC. I do not currently have Priiloader 0.10 beta. Despite being a beta, is it safe for me to install it? (Also, is there an installer binary I can use or just the source code)?

**Comment by DacoTaco** [comment]
hm, beta seems safe to install but if youre that worried, maybe its better to try a priiloader build in HBC?
run the dol in the following zip in HBC, see if it works?
[priiloader.zip](https://github.com/DacoTaco/priiloader/files/9333498/priiloader.zip)

**Comment by DacoTaco** [comment]
@PownicMania : did you find the log setting/file?

**Comment by DacoTaco** [comment]
i got myself a copy of mario kart wii (PAL) and have confirmed that it indeed crashes. looking at this i *think* its overwriting priiloader when launching the game

![image](https://user-images.githubusercontent.com/12701306/188318750-7fb0c013-45cb-4e92-87fb-03c2f8d8ac14.png)

**Comment by DacoTaco** [comment]
it was a video buffer/entrypoint issue.
Priiloader has now been moved to 0x81330000, the same address where system menu resides, and the memory region used by loaders.

the problem should be fixed, my copy booted correctly now
