### ISSUE TITLE
A Setting To Change Video Mode On The Wii Menu

### ISSUE THREAD

**Issue by ross3695** [DacoTaco/priiloader#313]
I use some hacks which need a region hacked Wii to NTSC, I have the system menus and everything but I usually use an RGB Scart lead which doesn't work properly with the american signal, it's very hard to see what wads Im clicking on etc.
I think this is will be an important and useful setting to have in a boot mod like Priiloader, Just to clarify i'm not just talking about patching games specifically(like the built in wiimmfi patch) I want to force system menu itself to display in the selected video mode automatically when i turn the Wii on
Actually If you do implement it though it may be a good idea to make some fail safe like a 'Press A if you see this message in 10 seconds' or hold the power buttons a certain way like on the PS3 to cycle video modes just in case

**Comment by DacoTaco** [comment]
what hacks and systems are you using that require a video mode change?

i have so far refused this change due to it being very dangerous to cause a video settings brick, only for piracy to work.
and with priiloader being able to boot titles and (in 0.10) discs, i see even less reason to do this
