### ISSUE TITLE
Doesn't let you run homebrew app on the vWii on the Wii U

### ISSUE THREAD

**Issue by Yeetov** [DacoTaco/priiloader#318]
**Describe the bug**
Says "Error: vwii detected - please do not run this on a Wii u!"
"Press A to exit back to the loader"

**To Reproduce**
Steps to reproduce the behaviour:
Open Priiloader on the vWii Homebrew Channel

**Version**
[0.10.0-beta2](https://github.com/DacoTaco/priiloader/releases/tag/0.10.0-beta2)
[Priiloader 0.9.1](https://github.com/DacoTaco/priiloader/releases/tag/0.9.1)
Haven't tested any others

**Expected behaviour**
Install Priiloader onto the vWii on the Wii U

**Comment by Masamune3210** [comment]
Release doesnt support vWii yet, afaik. Wait until its mentioned in the release notes before trying it

**Comment by Yeetov** [comment]
It says in the description that it is available for vWii: [https://www.youtube.com/watch?v=KLy_4PXanic](https://www.youtube.com/watch?v=KLy_4PXanic)

**Comment by Yeetov** [comment]
Oh yeah, it isn't available: [https://github.com/GaryOderNichts/priiloader/releases](https://github.com/GaryOderNichts/priiloader/releases)

**Comment by Yeetov** [comment]
Not available yet for vWii

**Comment by Masamune3210** [comment]
Correction: It says its being WORKED on
![image](https://user-images.githubusercontent.com/1053504/209392370-80c4bb67-b1b4-45ac-8275-d3cd386e62c1.png)
