### ISSUE TITLE
Question: Can OpenDolBoot produce MIOS images?

### ISSUE THREAD

**Issue by trevor403** [DacoTaco/priiloader#329]
I am trying to produce a modified BS2 for MIOS and I want to simplify generating the elf/app file.

Is the NAND Loader included in the OpenDolBoot utility able to be used to produce a valid `00000001-00000101` app?

**Comment by DacoTaco** [comment]
i don't think it is, however it has an option to pass in a filename of the nandloader it should use, so you can use a custom one.
