### ISSUE TITLE
Proper GameCube Mode Shutdown

### ISSUE THREAD

**Issue by Snivy102** [DacoTaco/priiloader#330]
I was wondering if it's possible for the Wii console to shutdown fully after pressing the power button during GameCube game playback from a disc? It looks like the Wii just restarts, which is common for some GameCube loaders. (Note: Nintendont powers down properly)

**Comment by DacoTaco** [comment]
it normally already should power down completely.
what are your shutdown settings in priiloader?

**Comment by Snivy102** [comment]
![PXL_20230421_204142157](https://user-images.githubusercontent.com/61268888/233733359-0a9d7f93-3018-401c-a329-25ff5b89e39d.jpg)

**Comment by DacoTaco** [comment]
bug confirmed. boot state needs to be invalidated before booting BC

**Comment by Snivy102** [comment]
Is there anything I need to do?

**Comment by DacoTaco** [comment]
nah, i need to do some investigation and reverse engineering on SM and see what needs to be done

**Comment by DacoTaco** [comment]
do you happen to know of any other gamecube game loaders besides nintendon't that don't have this issue?

**Comment by DacoTaco** [comment]
problem has been solved latest main branch. was an issue of closing the nand handle before setting the bootstate
