### ISSUE TITLE
Deflicker seems to only work on the system menu

### ISSUE THREAD

**Issue by Drodericson** [DacoTaco/priiloader#332]
**Describe the bug**
The deflicker filter seems to get re-enabled when booting any app, whether it be the disc channel, Virtual Console games, nintendont, etc. Not sure if this is possible, but it would be nice to have this feature work system wide, and to not have to use USBLoaderGX.

**To Reproduce**
Steps to reproduce the behaviour:
Start any app on the Wii menu

**Version**
[0.10.0-beta2]

**Expected behaviour**
Deflicker stays on when using other apps than the system menu

**Comment by DacoTaco** [comment]
this is normal, the hack priiloader applies is only applied to system menu. priiloader can not patch any other content
