### ISSUE TITLE
Wii gamepad sync problem

### ISSUE THREAD

**Issue by carlito666** [DacoTaco/priiloader#334]
Wii stopped syncying with my controller. 

Priiloader_v0_10b2

**Comment by DacoTaco** [comment]
in priiloader or in system menu/official software?

**Comment by carlito666** [comment]
In both places. The controller is Wii plus. 

Is it possible to downgrade to the previous priiloader version through Priiloader menu?

I use a keyboard to navigate through, but it works within Priiloader only.

**Comment by DacoTaco** [comment]
it is normal that you can't sync with the red button inside priiloader (or any homebrew). 
however, priiloader should not have any effect on syncing in other official software like system menu.

i suggest to try the wiimote on another wii and sync it using the red buttons from within system menu.

**Comment by carlito666** [comment]
Well, thanks.
