### ISSUE TITLE
0.10.0

### ISSUE THREAD

**Issue by Leonardo5681** [DacoTaco/priiloader#335]
sorry dacotaco, I had already opened an issue for this reason, but now I've been waiting too long, we are in June 2023 and the first beta was released in January 2022 so it's already 1 years, sorry for the way I'm responding, I'm currently using beta 2 without problems, (indeed congratulations for the stability) I will understand your reasons for not working on it, but I don't think that in 1 year and a half you haven't had time

**Comment by TheTechRobo** [comment]
What specific feature or fix do you need from the latest code? You might be able to compile the code yourself, though it might not be as well-tested as the releases.

**Comment by DacoTaco** [comment]
i have indeed been mostly waiting for vWii support, which sucks cause there is only 1 blocking issue for that one...

i too am curious to what feature you are looking forward to

**Comment by Leonardo5681** [comment]
sh*t vWii

**Comment by Leonardo5681** [comment]
I'm waiting this features: Add setting to prioritize USB access over SD
Priiloader can now drown your plants
Added Support for System Menu 1.0
Show Priiloader after installation
Priiloader will launch when booting System Menu
Added new hacks
Block disc autoboot
Remove Deflicker
Refactor device access
Priiloader no longer waits for the usb drive to respond when mounting

however dacotaco I use the beta2 daily and it never crashed, never a bug if I have to say

**Comment by DacoTaco** [comment]
... you just copy pasted the changelog

**Comment by Leonardo5681** [comment]
i copied it pk are the functions i am waiting for

**Comment by TheTechRobo** [comment]
But if you're running the beta 2, you already have those features, no?
