### ISSUE TITLE
Autobooting to BootMii IOS causes a sort of loop

### ISSUE THREAD

**Issue by Naim2000** [DacoTaco/priiloader#337]
**Describe the bug**
When turning on the Wii ~~from Standby~~ while Priiloader is set to autoboot BootMii as IOS, selecting the Wii menu will launch BootMii once again, and selecting the Homebrew Channel will freeze the Wii.

**To Reproduce**
~~* Go to WiiConnect24 in Wii settings and ensure Standby Connection is enabled.~~
* Restart the Wii and enter the Priiloader menu.
* Go to Settings and set AutoBoot to BootMii IOS.
  - ~~Ensure `Ignore Standby` is off.~~
* Go back and select System menu.
* Press the power button ~~and you will enter Standby.~~
* Turn the Wii back on, and you will enter BootMii.
* Press reset to select the Wii menu. You will enter BootMii once again.
* Press power once and reset once to select HBC. Your Wii is stuck on a black screen.
Get out of this by holding reset while highlighting the Wii menu option.

**Version**
Priiloader v0.9.1 (r0x092658e7)
System menu v513, IOS80

**Expected behavior**
The options in the BootMii menu would launch their respective applications.

**Video**
[bootmii_ios_loop.mp4](https://cdn.discordapp.com/attachments/763146093655359488/1126905973525708920/bootmii_ios_loop.mp4)

**Additional context**

**Comment by DacoTaco** [comment]
sounds normal to me.
wii does a boot , which boots priiloader, priiloader boots bootmii, bootmii boots System menu, which loads priiloader, which loads bootmii etc etc.

the bootmii autoboot is to be used with things that setup the wii in a certain way like Emunand or something.

the only thing i don't understand is why booting HBC causes a freeze. this is booting HBC in bootmii?

**Comment by DacoTaco** [comment]
the return to option is not triggered, as bootmii/boot2 sets the system up like it is a cold boot. there is nothing priiloader can do but follow the boot rules and launch autoboot settings.

like i said though, that options was meant for emunand/sneek/whatever and not actual bootmii.

as for the HBC crash, i want to investigate if i can reproduce it, but my money is on it being a bootmii/boot2/HBC issue

**Comment by DacoTaco** [comment]
unable to reproduce the HBC bug. seems to be something specific to the case and/or bootmii/hbc
