### ISSUE TITLE
Wrong alignment message when setting up "Return To" option

### ISSUE THREAD

**Issue by impeeza** [DacoTaco/priiloader#342]
Using Priiloader 0.10.0 RC3, when you on the "Settings" menu, on the option "Return to" when you select the new item "Installed file", the alignment is off:

![image](https://github.com/DacoTaco/priiloader/assets/41979604/086d3ac2-b0d4-41e9-a443-ab8af3a12f3c)

Is only Aesthetic and do not affect functionalism.

Seems to be the line 955 on the file \src\priiloader\source\main.cpp:

```
				case RETURNTO_FILE:
					PrintFormat( cur_off==1, 0, 128,    "             Return to:    Installed file   ");
```

And should be:

```
				case RETURNTO_FILE:
					PrintFormat( cur_off==1, 0, 128,    "             Return to:          Installed file  ");
```

Hard to show the 6 spaces before the "Installed"

**Comment by Ingunar** [comment]
Yes, can confirm that this is the case.
Also `Installed File` instead of `Installed file` (For consistency)

**Comment by DacoTaco** [comment]
thanks for reporting. this will be fixed on the next release
