### ISSUE TITLE
Priiloader not installing: menu version invalid or not vanilla

### ISSUE THREAD

**Issue by Gubbiej** [DacoTaco/priiloader#344]
If I try to install the priiloader I get the error menuversion invalid or not vanilla

**Version**
I get the error on versions V0.10, v0.9.1 and v0.9. Other versions I haven't tried yet.

**Comment by DacoTaco** [comment]
you probably have a modified system menu and the installer refuses to install on a modified system menu since it can't trust it to be safe.
please reinstall system menu and try again.

**Comment by Gubbiej** [comment]
Maybe a stupid question, but how do I reinstall the system menu? It's now on version 4.2e. I reset my wii to factory settings en started all over with homebrew channel. I used thuis guide https://wii.guide/.
