### ISSUE TITLE
"Disable System Menu Background Music" doesn't work on 4.3E

### ISSUE THREAD

**Issue by jornmann** [DacoTaco/priiloader#345]
**Describe the bug**
Enabling the Disable System Menu Background Music system menu hack doesn't disable the music.

**To Reproduce**
1. Own a Wii running SysMenu version 4.3E
2. Install Priiloader 0.10.0 RC3
3. Enable the "Disable System Menu Background Music" system menu hack
4. Go back to the Wii Menu

**Version**
0.10.0 RC3 on System Menu 4.3E

**Expected behavior**
The music not being there

**Comment by DacoTaco** [comment]
@Ingunar : have you seen this one? 

from the looks of your document, it should have been disabled?
( https://hackmd.io/@Ingunar/PriiloaderTesting )

**Comment by DacoTaco** [comment]
seems like its broke on 4.3E then :D

**Comment by DacoTaco** [comment]
@jornmann : is this a wii, wii mini, vwii,...?

**Comment by jornmann** [comment]
regular Wii

**Comment by jornmann** [comment]
the hacks_hash you supplied worked perfectly! thank you :)
