### ISSUE TITLE
Reinstall system menu

### ISSUE THREAD

**Issue by Gubbiej** [DacoTaco/priiloader#346]
**Describe the bug**
Thanks for the quick reply in my previous issue. Maybe a stupid question, but how do I reinstall the system menu? It's now on version 4.2e. I reset my wii to factory settings en started all over with homebrew channel. I used thuis guide https://wii.guide/.

**Comment by DacoTaco** [comment]
reinstall system menu using modmii.
https://modmii.github.io/index.html

this issue tracker isn't the target to solve your issue though

**Comment by Gubbiej** [comment]
Thank you, ill try it

**Comment by Gubbiej** [comment]
Thanks allot for the quick replies and info. I succesfully softmodded my Wii again and played my first Mario game with my 4 yo daughter,she loves it ,👍
