### ISSUE TITLE
Glitchy USB loader GX when priiloader is installed on vWii

### ISSUE THREAD

**Issue by bolo-kun** [DacoTaco/priiloader#357]
**Describe the bug**
When priiloader is installed on vWii, USB loader GX GUI does not work properly

**To Reproduce**
Install priiloader on vWii with this fork of USB Loader GX (I did not test it on other forks) 
https://github.com/wiidev/usbloadergx/releases/tag/v3.0-r1281

**Version**
[0.10.0](https://github.com/DacoTaco/priiloader/releases/tag/0.10.0)

**Expected behavior**
Not glitching USB loader GX

**Screenshots**
![image](https://github.com/DacoTaco/priiloader/assets/86896879/068bf63f-4f57-4081-90bf-86a86b17b36a)
![image](https://github.com/DacoTaco/priiloader/assets/86896879/cb843d1f-784b-43d1-bde6-3d26a2f9420a)

**Additional context**
Tested twice by removing and re installing priiloader, when the priiloader is removed the problem does not occur

**Comment by impeeza** [comment]
duplicated https://github.com/DacoTaco/priiloader/issues/348 and as stated on 348, is a USB Loader GX issue, please go to that repo and add comments to the issue on it.
