### ISSUE TITLE
Error Autobooting HBC + System Files are Corrupted

### ISSUE THREAD

**Issue by DefeatOf13** [DacoTaco/priiloader#363]
**Describe the bug**
Whenever i try to boot into the Homebrew Channel via Priiloader i get an error message saying "Error Autobooting HBC. Maybe title not installed?". I can't even boot into the system menu, if i try to do it another error shows up saying "The system file are corrupted, blah blah blah.". BootMii works fine though.

**To Reproduce**
1. Boot into Priiloader
2. Press "Homebrew Channel" and get the error "Error Autobooting HBC. Maybe title not installed?"
3. Press "System Menu" and get the "System files are corrupted" error

**Version**
- Priiloader 0.10.0
- HBC 1.1.2
- System Menu 4.3E (v514)

**Expected behavior**
Boot into HBC and sysmenu without any issues.

**Screenshots**
![immagine_2024-01-29_145737207](https://github.com/DacoTaco/priiloader/assets/106403912/a91370e1-3a35-4b26-83da-72bed9cb6ebf)
![Screenshot 2024-01-29 145639](https://github.com/DacoTaco/priiloader/assets/106403912/e5c6d513-9c68-4389-bc02-6e268d3510fd)

**Additional Infos**
The Wii i'm using is a PAL Family Edition Wii, btw the console is not bricked

**Comment by impeeza** [comment]
May be you have a soft bricked nand, what if you try to load / install a file utem and then load a basic homebrew from your SD card? By example syscheck

**Comment by DefeatOf13** [comment]
> May be you have a soft bricked nand, what if you try to load / install a file utem and then load a basic homebrew from your SD card? By example syscheck

Ok, i did as you said. I'm able to load / install apps without any problems (and they boot too). I tried Syscheck ModMii edition and USB Loader GX

**Comment by DacoTaco** [comment]
check the System menu IOS setting in priiloader. what are the settings?

**Comment by DefeatOf13** [comment]
> check the System menu IOS setting in priiloader. what are your priiloader settings in general?

The "Use System Menu IOS" option is already checked.
Here's my settings: 
![immagine_2024-01-29_182548540](https://github.com/DacoTaco/priiloader/assets/106403912/e9414e73-59c7-4e15-a3e6-a86207dadf30)

**Comment by DacoTaco** [comment]
hmm, i too think you might have a softbrick. did you recently install any channels? 
also, try the following things : 
* disable autoboot and boot HBC when menu shows up, don't hold reset on boot. does it boot HBC?
* keep autoboot disabled, and go to boot channel, can you boot HBC from there? what HBC is installed?
* put autoboot back on System menu, and set use system menu ios to off. as IOS, select a CIOS (like 249). boot SM. does it boot SM?

**Comment by DefeatOf13** [comment]
Update.

I went back to "Boot Title" and now all the titles installed onto the console are called "????????"

![immagine_2024-01-29_191449087](https://github.com/DacoTaco/priiloader/assets/106403912/4d7513ba-f4d1-4803-8844-276b2e547d2e)

**Comment by impeeza** [comment]
Yeah you have a corrupted NAND try, run ModWii https://modmii.github.io/ (https://gbatemp.net/threads/best-way-to-mod-any-wii-modmii-for-windows-official-support-thread.207126/) on your computer and reinstall everything, you can load the HBC installer from Priiloader.

**Comment by DefeatOf13** [comment]
> Yeah you have a corrupted NAND try, run ModWii https://modmii.github.io/ (https://gbatemp.net/threads/best-way-to-mod-any-wii-modmii-for-windows-official-support-thread.207126/) on your computer and reinstall everything, you can load the HBC installer from Priiloader.

Like... What exactly do i need to reinstall?

**Comment by DacoTaco** [comment]
> Yeah you have a corrupted NAND try, run ModWii https://modmii.github.io/ (https://gbatemp.net/threads/best-way-to-mod-any-wii-modmii-for-windows-official-support-thread.207126/) on your computer and reinstall everything, you can load the HBC installer from Priiloader.

wrong. priiloader is fucking with the loaded IOS and SM can't load certain files.

**Comment by DefeatOf13** [comment]
What do you suggest to do? (always if there is something that can be done)

**Comment by impeeza** [comment]
Oh, @DacoTaco a wrong priiloader like the vWii on the Wii?

so he could reinstall priiloader to try to fix the problem?

The priiloader installer can be loaded from priiloader?

**Comment by DacoTaco** [comment]
i suspect this was an Priiloader setting issue together with invalid HBC installation or somehow it had a titleID that is unknown to Priiloader.

we will never know now though :)
