### ISSUE TITLE
Installing priiloader on my vwii added graphical glitches to usb loader gx

### ISSUE THREAD

**Issue by PalmTamino** [DacoTaco/priiloader#365]
**Describe the bug**
Icons that should be squircle were rectangle, no start button after clicking on app

**To Reproduce**
try usb loader gx

**Version**
0.10

**Expected behavior**
no glitches

**Screenshots**
![IMG_2282](https://github.com/DacoTaco/priiloader/assets/36358673/1c9483d1-2bf9-44e2-bbb1-66cefbba63e6)
![IMG_2283](https://github.com/DacoTaco/priiloader/assets/36358673/b72acde6-20b0-4b19-84a2-151d670fe27d)

**Comment by DacoTaco** [comment]
this is, afaik, a bug with USBloader GX. they need to fix their System menu theme loading code on vwii. we have provided them the fix more than 6 months ago, they should've fixed it by now...

**Comment by PalmTamino** [comment]
> this is, afaik, a bug with USBloader GX. they need to fix their System menu theme loading code on vwii. we have provided them the fix more than 6 months ago, they should've fixed it by now...

maybe i’m using the wrong usb loader gx then, some old version? There are a lot on github, could you link me the one u suggest?

Many thanks 🙏

**Comment by DacoTaco** [comment]
i don't know which one is the official one, but as far as i know they haven't released an updated version yet to fix this bug -_-

**Comment by eku** [comment]
It hasn't been fixed so far.

**Comment by PalmTamino** [comment]
> It hasn't been fixed so far.

yes, i think usb loader gx is pretty inactive in development, i hope there will even be a new update. If a dev could compile it with the fix themselves, that would be awesome (and fork it on github)
