### ISSUE TITLE
Error autobooting file 

### ISSUE THREAD

**Issue by mpzfm1** [DacoTaco/priiloader#368]
**Describe the bug**
Error "autobooting file, try to reinstall"

**To Reproduce**

Clic on installed file option

**Version**
0.10.0

**Expected behavior**
I dont know, what is this option for???

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Additional context**

**Comment by DacoTaco** [comment]
this option is to boot the binary that is installed through the `Load/Install File` option. this is for when you stopped the autoboot to do something and want to launch your installed/autoboot file :)

**Comment by mpzfm1** [comment]
Thanks very much, and what app do you recommend to have installed?

**Comment by impeeza** [comment]
> Thanks very much, and what app do you recommend to have installed?

Any you like, I personnaly have a WiiFlow forwarder DOL installed, so each time I start my console Wii-flow run.

**Comment by mpzfm1** [comment]
Thanks
